<a href="https://colab.research.google.com/github/mohamedzaghloul-lab638/QSAR-modelling---EGFR-/blob/main/EGFR_predictive_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.3.3-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.19)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.7.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-26.2.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.11.7)
Collecting url-normalize>=2.0 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.16.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 1.9 MB/s eta 0:00:00
Downloading requests_cache-1.3.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 4.2 MB/s eta 0:00:00
Downloading cattrs-26.2.0-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.8/74.8 kB 2.9 MB/s eta 0:00:00
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-26.2.0 chembl_webresource_client-0.10.9 requests-cache-1.3.3 url-normalize-3.0.0

In [ ]:
from chembl_webresource_client.new_client import new_client
def get_chembl_data(target_name , max_results=1000):
  target=new_client.target
  target_results=target.search(target_name)
  for i,t in enumerate(target_results):
    print(i,t['target_chembl_id'],t['pref_name'],t['organism'])
  return target_results
res= get_chembl_data('EGFR')
target_id=res[0]['target_chembl_id']
print(f'target id is :{target_id}')

0 CHEMBL4523747 EGFR/PPP1CA Homo sapiens
1 CHEMBL5465557 CCN2-EGFR Homo sapiens
2 CHEMBL3608 Epidermal growth factor receptor Mus musculus
3 CHEMBL6193842 Protein cereblon/Epidermal growth factor receptor Mus musculus
4 CHEMBL203 Epidermal growth factor receptor Homo sapiens
5 CHEMBL4523680 Protein cereblon/Epidermal growth factor receptor Homo sapiens
6 CHEMBL2363049 Epidermal growth factor receptor Homo sapiens
7 CHEMBL3137284 MER intracellular domain/EGFR extracellular domain chimera Homo sapiens
8 CHEMBL4523998 von Hippel-Lindau disease tumor suppressor/Epidermal growth factor receptor Homo sapiens
9 CHEMBL6193841 Protein cereblon/Epidermal growth factor receptor Mus musculus
10 CHEMBL1824 Receptor tyrosine-protein kinase erbB-2 Homo sapiens
11 CHEMBL3848 Receptor tyrosine-protein kinase erbB-2 Rattus norvegicus
12 CHEMBL3009 Receptor tyrosine-protein kinase erbB-4 Homo sapiens
13 CHEMBL5838 Receptor tyrosine-protein kinase erbB-3 Homo sapiens
14 CHEMBL2111431 Epidermal growth factor receptor and ErbB2 (HER1 and HER2) Homo sapiens
15 CHEMBL2311234 Receptor tyrosine-protein kinase erbB-2 Mus musculus
16 CHEMBL4106134 FASN/HER2 Homo sapiens
17 CHEMBL4630723 ErbB-2/ErbB-3 heterodimer Homo sapiens
18 CHEMBL4802031 Baculoviral IAP repeat-containing protein 2/Epidermal growth factor receptor Homo sapiens
19 CHEMBL5465227 von Hippel-Lindau disease tumor suppressor/Receptor tyrosine-protein kinase erbB-2 Homo sapiens
20 CHEMBL6066839 Microtubule-associated protein 1 light chain 3 beta/Epidermal growth factor receptor Homo sapiens
21 CHEMBL6066845 Glucose-induced degradation protein 4 homolog/Epidermal growth factor receptor Homo sapiens
22 CHEMBL6193792 E3 ubiquitin-protein ligase Mdm2/Epidermal growth factor receptor Homo sapiens
23 CHEMBL6193830 UBR/Epidermal growth factor receptor Homo sapiens
24 CHEMBL6193837 Protein zyg-11 homolog B/Protein zer-1 homolog/Epidermal growth factor receptor Homo sapiens
25 CHEMBL6195769 E3 ubiquitin-protein ligase RNF149/Epidermal growth factor receptor Homo sapiens
target id is :CHEMBL4523747

In [ ]:
import pandas as pd
import numpy as np

def get_chembl_act(target_id,max_results=1000):
  activity=new_client.activity
  results=activity.filter(target_chembl_id=target_id,
                          standard_type='IC50',
                          standard_relation='=',
                          assay_type='B',
                          limit=max_results

                          ).only([
                              'molecule_chembl_id',
            'canonical_smiles',
            'standard_value',
            'standard_units',
            'standard_type',
            'assay_chembl_id'])

  df=pd.DataFrame(list(results))
  print(f" number of compounds is : {len(df)}")
  return df

df = get_chembl_act('CHEMBL203')
print(df.shape)
print(df.head())

 number of compounds is : 18454
(18454, 9)
  assay_chembl_id                                   canonical_smiles  \
0    CHEMBL674637  Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...
1    CHEMBL674637  Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...
2    CHEMBL677833        CN(c1ccccc1)c1ncnc2ccc(N/N=N/Cc3ccccn3)cc12
3    CHEMBL674643             CC(=C(C#N)C#N)c1ccc(NC(=O)CCC(=O)O)cc1
4    CHEMBL674643                             O=C(O)/C=C/c1ccc(O)cc1

  molecule_chembl_id standard_type standard_units standard_value  type units  \
0        CHEMBL68920          IC50             nM           41.0  IC50    uM
1        CHEMBL69960          IC50             nM          170.0  IC50    uM
2       CHEMBL137635          IC50             nM         9300.0  IC50    uM
3       CHEMBL306988          IC50             nM       500000.0  IC50    uM
4        CHEMBL66879          IC50             nM      3000000.0  IC50    uM

    value
0   0.041
1    0.17
2     9.3
3   500.0
4  3000.0

In [ ]:
from google.colab import files
df.to_csv('EGFR_database.csv',index=False)
files.download('EGFR_database.csv')

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/EGFR_database.csv')
df

,assay_chembl_id,canonical_smiles,molecule_chembl_id,standard_type,standard_units,standard_value,type,units,value
0,CHEMBL674637,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,CHEMBL68920,IC50,nM,41.000,IC50,uM,0.041
1,CHEMBL674637,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,CHEMBL69960,IC50,nM,170.000,IC50,uM,0.170
2,CHEMBL677833,CN(c1ccccc1)c1ncnc2ccc(N/N=N/Cc3ccccn3)cc12,CHEMBL137635,IC50,nM,9300.000,IC50,uM,9.300
3,CHEMBL674643,CC(=C(C#N)C#N)c1ccc(NC(=O)CCC(=O)O)cc1,CHEMBL306988,IC50,nM,500000.000,IC50,uM,500.000
4,CHEMBL674643,O=C(O)/C=C/c1ccc(O)cc1,CHEMBL66879,IC50,nM,3000000.000,IC50,uM,3000.000
...,...,...,...,...,...,...,...,...,...
18449,CHEMBL6184534,O=C(CCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,CHEMBL6191667,IC50,nM,9.800,IC50,nM,9.800
18450,CHEMBL6184534,O=C(CCCCCOc1cc2ncnc(Nc3ccccc3Cl)c2c2c1OCCO2)NO,CHEMBL6192203,IC50,nM,130.100,IC50,nM,130.100
18451,CHEMBL6184534,O=C(CCCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,CHEMBL6191199,IC50,nM,4.810,IC50,nM,4.810
18452,CHEMBL6184534,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,CHEMBL939,IC50,nM,13.080,IC50,nM,13.080
18453,CHEMBL6184543,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,CHEMBL29197,IC50,nM,0.025,IC50,nM,0.025

In [2]:
df_clean=df.dropna()
df_clean=df_clean[['canonical_smiles','standard_type','standard_value','standard_units']]
print(df_clean)

# IC50 to PIC50
df_clean=df_clean[df_clean['standard_units']=='nM']
df_clean_PIC50=df_clean.copy()
df_clean_PIC50['standard_value']=pd.to_numeric(df_clean_PIC50['standard_value'],errors='coerce')
df_clean_PIC50=df_clean_PIC50[df_clean_PIC50['standard_value']>0]
df_clean_PIC50['PIC50']=-np.log10(df_clean_PIC50['standard_value']*1e-9)
df_clean_PIC50

                                        canonical_smiles standard_type  \
0      Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...          IC50
1      Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...          IC50
2            CN(c1ccccc1)c1ncnc2ccc(N/N=N/Cc3ccccn3)cc12          IC50
3                 CC(=C(C#N)C#N)c1ccc(NC(=O)CCC(=O)O)cc1          IC50
4                                 O=C(O)/C=C/c1ccc(O)cc1          IC50
...                                                  ...           ...
18449    O=C(CCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO          IC50
18450     O=C(CCCCCOc1cc2ncnc(Nc3ccccc3Cl)c2c2c1OCCO2)NO          IC50
18451   O=C(CCCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO          IC50
18452     COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1          IC50
18453                  COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC          IC50

       standard_value standard_units
0              41.000             nM
1             170.000             nM
2            9300.000             nM
3          500000.000             nM
4         3000000.000             nM
...               ...            ...
18449           9.800             nM
18450         130.100             nM
18451           4.810             nM
18452          13.080             nM
18453           0.025             nM

[17701 rows x 4 columns]

,canonical_smiles,standard_type,standard_value,standard_units,PIC50
0,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,IC50,41.000,nM,7.387216
1,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,IC50,170.000,nM,6.769551
2,CN(c1ccccc1)c1ncnc2ccc(N/N=N/Cc3ccccn3)cc12,IC50,9300.000,nM,5.031517
3,CC(=C(C#N)C#N)c1ccc(NC(=O)CCC(=O)O)cc1,IC50,500000.000,nM,3.301030
4,O=C(O)/C=C/c1ccc(O)cc1,IC50,3000000.000,nM,2.522879
...,...,...,...,...,...
18449,O=C(CCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,IC50,9.800,nM,8.008774
18450,O=C(CCCCCOc1cc2ncnc(Nc3ccccc3Cl)c2c2c1OCCO2)NO,IC50,130.100,nM,6.885723
18451,O=C(CCCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,IC50,4.810,nM,8.317855
18452,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,IC50,13.080,nM,7.883392
18453,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,IC50,0.025,nM,10.602060

In [3]:
if df_clean_PIC50.isna().sum().sum() ==0 :
  print ("ready to GO")
else :
     print ("still need some curation")

ready to GO

In [4]:
! pip install rdkit

Collecting rdkit
  Downloading rdkit-2026.3.6-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from rdkit) (2.1.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.13/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2026.3.6-cp313-cp313-manylinux_2_28_x86_64.whl (38.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.1/38.1 MB 47.5 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2026.3.6

In [5]:
from rdkit import Chem
from rdkit.Chem import Descriptors, DataStructs , rdFingerprintGenerator
# smiles function
gen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)

def get_smi (smi) :
  mol=Chem.MolFromSmiles(smi)
  fp=gen.GetFingerprint(mol)
  return np.array(fp)
# descs function
def get_desc(smi):
  mol=Chem.MolFromSmiles(smi)
  return np.array([Descriptors.ExactMolWt(mol),
      Descriptors.MolLogP(mol),
      Descriptors.TPSA(mol),
      Descriptors.NumHDonors(mol),
      Descriptors.NumHAcceptors(mol)])
 # concatentaion
def get_features(smi):
 fps=get_smi(smi)
 desc=get_desc(smi)
 features=np.concatenate([fps,desc])
 return features

In [6]:
# apply function
df_clean_PIC50.reset_index(drop=True,inplace=True) # to avoid errors of indexing after filtering
features_list=[get_features(smi) for smi in df_clean_PIC50['canonical_smiles']]
validation=[i for i,f in enumerate(features_list) if f is None]
df_clean_PIC50=df_clean_PIC50.drop(index=validation).reset_index(drop=True)

In [7]:
x=np.array(features_list)
y=np.array(df_clean_PIC50['PIC50'])
print(x.shape,y.shape)

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=RandomForestRegressor(n_estimators=100,random_state=42)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

(17628, 2053) (17628,)

In [8]:
MSE=mean_squared_error(y_test,y_pred)
R2=r2_score(y_test,y_pred)
print(f"MSE : {MSE}")
print(f"R2 : {R2}")

MSE : 0.7425863290584271
R2 : 0.6132473128902671

In [9]:
# grouped scaffold-based split
from rdkit.Chem.Scaffolds import MurckoScaffold
def get_scaffold(smi):
  mol=Chem.MolFromSmiles(smi)
  scaffold=MurckoScaffold.GetScaffoldForMol(mol)
  return Chem.MolToSmiles(scaffold)

df_clean_PIC50['scaffold']=[get_scaffold(smi) for smi in df_clean_PIC50['canonical_smiles']]

In [10]:
from collections import defaultdict
scaffold_groups = defaultdict(list)
for idx, scaf in zip(df_clean_PIC50.index, df_clean_PIC50['scaffold']):
    scaffold_groups[scaf].append(idx)

groups = sorted(scaffold_groups.values(), key=len, reverse=True)

print(f"  number of scaffolds is : {len(groups)}")

  number of scaffolds is : 3776

In [11]:
# grouping
train_idx, test_idx = [], []
test_size_target = 0.2 * len(df_clean_PIC50)

for group in groups:
    if len(test_idx) < test_size_target:
        test_idx.extend(group)
    else:
        train_idx.extend(group)

print(f"Train: {len(train_idx)} compounds")
print(f"Test: {len(test_idx)} compounds")

Train: 14090 compounds
Test: 3538 compounds

In [12]:
x_train, x_test = x[train_idx], x[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

print(f"X_train: {x_train.shape}, X_test: {x_test.shape}")

X_train: (14090, 2053), X_test: (3538, 2053)

In [13]:
# re-training

model = RandomForestRegressor(n_estimators=200, random_state=42, n_jobs=-1)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MSE: {mse}")
print(f"R2: {r2}")

MSE: 1.13401620752681
R2: 0.38358642797914144

In [17]:
print(f"numver of unique scaffolds is: {df_clean_PIC50['scaffold'].nunique()}")
print(f"number of mols is : {len(df_clean_PIC50)}")

numver of unique scaffolds is: 3776
number of mols is : 17628

In [18]:
from rdkit import Chem
from rdkit.Chem.Scaffolds import MurckoScaffold
from rdkit.Chem.Scaffolds.MurckoScaffold import MakeScaffoldGeneric

def get_generic_scaffold(smi):
    mol = Chem.MolFromSmiles(smi)
    if mol is None:
        return None
    try:
        scaffold = MurckoScaffold.GetScaffoldForMol(mol)
        generic = MakeScaffoldGeneric(scaffold)
        return Chem.MolToSmiles(generic)
    except:
        return None

df_clean_PIC50['generic_scaffold'] = [get_generic_scaffold(smi) for smi in df_clean_PIC50['canonical_smiles']]

print(f" Nones: {df_clean_PIC50['generic_scaffold'].isna().sum()}")

n_murcko = df_clean_PIC50['scaffold'].nunique()
n_generic = df_clean_PIC50['generic_scaffold'].nunique()

print(f" unique Murcko scaffolds : {n_murcko}")
print(f" Generic scaffolds : {n_generic}")
print(f"diversity reasoning : {(1 - n_generic/n_murcko):.1%}")

 Nones: 0
 unique Murcko scaffolds : 3776
 Generic scaffolds : 2226
diversity reasoning : 41.0%

In [ ]:
from sklearn.model_selection import GridSearchCV, GroupKFold
from sklearn.ensemble import RandomForestRegressor

scaffolds_train = df_clean_PIC50['scaffold'].values[train_idx]

gkf = GroupKFold(n_splits=5)

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
}

GD = GridSearchCV(
    estimator=RandomForestRegressor(random_state=42),
    param_grid=param_grid,
    n_jobs=-1,
    cv=gkf.split(x_train, y_train, groups=scaffolds_train),
    scoring='r2',
    verbose=2
)

GD.fit(x_train, y_train)

print(f"best param : {GD.best_params_}")
print(f" best R² in CV: {GD.best_score_:.3f}")

Fitting 5 folds for each of 36 candidates, totalling 180 fits

In [19]:
# Descision tree-based alogo
from xgboost import XGBRegressor
model = XGBRegressor(n_estimators=200,learning_rate=0.05 , subsample=0.8 , colsample_bytree=0.8, max_depth=6, random_state=42, n_jobs=-1)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MSE: {mse}")
print(f"R2: {r2}")

MSE: 1.250659302174984
R2: 0.320183113153107

In [21]:
from sklearn.ensemble import HistGradientBoostingRegressor
model = HistGradientBoostingRegressor(max_iter=300 , learning_rate=0.05, max_depth=6, random_state=42)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MSE: {mse}")
print(f"R2: {r2}")

MSE: 1.2352161940346849
R2: 0.3285774741760653

In [24]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
svm= Pipeline ([
    ('scaler' , StandardScaler()) ,
    ('svm' , SVR(kernel='rbf', C=100, gamma=0.1, epsilon=.1))])

model=svm.fit(x_train, y_train)
y_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MSE: {mse}")
print(f"R2: {r2}")

MSE: 1.9339108625005863
R2: -0.05120975768394631